//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataBenhVien.DataModel
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class benhvienEntities1 : DbContext
    {
        public benhvienEntities1()
            : base("name=benhvienEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
    
        public virtual int sp_alterdiagram(string diagramname, Nullable<int> owner_id, Nullable<int> version, byte[] definition)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var versionParameter = version.HasValue ?
                new ObjectParameter("version", version) :
                new ObjectParameter("version", typeof(int));
    
            var definitionParameter = definition != null ?
                new ObjectParameter("definition", definition) :
                new ObjectParameter("definition", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_alterdiagram", diagramnameParameter, owner_idParameter, versionParameter, definitionParameter);
        }
    
        public virtual int sp_creatediagram(string diagramname, Nullable<int> owner_id, Nullable<int> version, byte[] definition)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var versionParameter = version.HasValue ?
                new ObjectParameter("version", version) :
                new ObjectParameter("version", typeof(int));
    
            var definitionParameter = definition != null ?
                new ObjectParameter("definition", definition) :
                new ObjectParameter("definition", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_creatediagram", diagramnameParameter, owner_idParameter, versionParameter, definitionParameter);
        }
    
        public virtual int SP_Doctors_DELETE(Nullable<System.Guid> iD)
        {
            var iDParameter = iD.HasValue ?
                new ObjectParameter("ID", iD) :
                new ObjectParameter("ID", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_Doctors_DELETE", iDParameter);
        }
    
        public virtual ObjectResult<SP_Doctors_GetAll_Result> SP_Doctors_GetAll()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_Doctors_GetAll_Result>("SP_Doctors_GetAll");
        }
    
        public virtual ObjectResult<SP_Doctors_GetByID_Result> SP_Doctors_GetByID(Nullable<System.Guid> iD)
        {
            var iDParameter = iD.HasValue ?
                new ObjectParameter("ID", iD) :
                new ObjectParameter("ID", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_Doctors_GetByID_Result>("SP_Doctors_GetByID", iDParameter);
        }
    
        public virtual int SP_Doctors_INSERT(Nullable<System.Guid> iD, string name, string images, string description, Nullable<bool> status, string medicalName, Nullable<System.Guid> iDkhoa)
        {
            var iDParameter = iD.HasValue ?
                new ObjectParameter("ID", iD) :
                new ObjectParameter("ID", typeof(System.Guid));
    
            var nameParameter = name != null ?
                new ObjectParameter("Name", name) :
                new ObjectParameter("Name", typeof(string));
    
            var imagesParameter = images != null ?
                new ObjectParameter("Images", images) :
                new ObjectParameter("Images", typeof(string));
    
            var descriptionParameter = description != null ?
                new ObjectParameter("Description", description) :
                new ObjectParameter("Description", typeof(string));
    
            var statusParameter = status.HasValue ?
                new ObjectParameter("Status", status) :
                new ObjectParameter("Status", typeof(bool));
    
            var medicalNameParameter = medicalName != null ?
                new ObjectParameter("MedicalName", medicalName) :
                new ObjectParameter("MedicalName", typeof(string));
    
            var iDkhoaParameter = iDkhoa.HasValue ?
                new ObjectParameter("IDkhoa", iDkhoa) :
                new ObjectParameter("IDkhoa", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_Doctors_INSERT", iDParameter, nameParameter, imagesParameter, descriptionParameter, statusParameter, medicalNameParameter, iDkhoaParameter);
        }
    
        public virtual int SP_Doctors_UPDATE(Nullable<System.Guid> iD, string name, string images, string description, Nullable<bool> status, string medicalName, Nullable<System.Guid> iDkhoa)
        {
            var iDParameter = iD.HasValue ?
                new ObjectParameter("ID", iD) :
                new ObjectParameter("ID", typeof(System.Guid));
    
            var nameParameter = name != null ?
                new ObjectParameter("Name", name) :
                new ObjectParameter("Name", typeof(string));
    
            var imagesParameter = images != null ?
                new ObjectParameter("Images", images) :
                new ObjectParameter("Images", typeof(string));
    
            var descriptionParameter = description != null ?
                new ObjectParameter("Description", description) :
                new ObjectParameter("Description", typeof(string));
    
            var statusParameter = status.HasValue ?
                new ObjectParameter("Status", status) :
                new ObjectParameter("Status", typeof(bool));
    
            var medicalNameParameter = medicalName != null ?
                new ObjectParameter("MedicalName", medicalName) :
                new ObjectParameter("MedicalName", typeof(string));
    
            var iDkhoaParameter = iDkhoa.HasValue ?
                new ObjectParameter("IDkhoa", iDkhoa) :
                new ObjectParameter("IDkhoa", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_Doctors_UPDATE", iDParameter, nameParameter, imagesParameter, descriptionParameter, statusParameter, medicalNameParameter, iDkhoaParameter);
        }
    
        public virtual int sp_dropdiagram(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_dropdiagram", diagramnameParameter, owner_idParameter);
        }
    
        public virtual int SP_Equipments_DELETE(Nullable<System.Guid> iD)
        {
            var iDParameter = iD.HasValue ?
                new ObjectParameter("ID", iD) :
                new ObjectParameter("ID", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_Equipments_DELETE", iDParameter);
        }
    
        public virtual ObjectResult<SP_Equipments_GetAll_Result> SP_Equipments_GetAll()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_Equipments_GetAll_Result>("SP_Equipments_GetAll");
        }
    
        public virtual ObjectResult<SP_Equipments_GetByID_Result> SP_Equipments_GetByID(Nullable<System.Guid> iD)
        {
            var iDParameter = iD.HasValue ?
                new ObjectParameter("ID", iD) :
                new ObjectParameter("ID", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_Equipments_GetByID_Result>("SP_Equipments_GetByID", iDParameter);
        }
    
        public virtual int SP_Equipments_INSERT(Nullable<System.Guid> iD, string name, string details, string images)
        {
            var iDParameter = iD.HasValue ?
                new ObjectParameter("ID", iD) :
                new ObjectParameter("ID", typeof(System.Guid));
    
            var nameParameter = name != null ?
                new ObjectParameter("Name", name) :
                new ObjectParameter("Name", typeof(string));
    
            var detailsParameter = details != null ?
                new ObjectParameter("Details", details) :
                new ObjectParameter("Details", typeof(string));
    
            var imagesParameter = images != null ?
                new ObjectParameter("Images", images) :
                new ObjectParameter("Images", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_Equipments_INSERT", iDParameter, nameParameter, detailsParameter, imagesParameter);
        }
    
        public virtual int SP_Equipments_UPDATE(Nullable<System.Guid> iD, string name, string details, string images)
        {
            var iDParameter = iD.HasValue ?
                new ObjectParameter("ID", iD) :
                new ObjectParameter("ID", typeof(System.Guid));
    
            var nameParameter = name != null ?
                new ObjectParameter("Name", name) :
                new ObjectParameter("Name", typeof(string));
    
            var detailsParameter = details != null ?
                new ObjectParameter("Details", details) :
                new ObjectParameter("Details", typeof(string));
    
            var imagesParameter = images != null ?
                new ObjectParameter("Images", images) :
                new ObjectParameter("Images", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_Equipments_UPDATE", iDParameter, nameParameter, detailsParameter, imagesParameter);
        }
    
        public virtual int SP_Feedbacks_DELETE(Nullable<System.Guid> iD)
        {
            var iDParameter = iD.HasValue ?
                new ObjectParameter("ID", iD) :
                new ObjectParameter("ID", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_Feedbacks_DELETE", iDParameter);
        }
    
        public virtual ObjectResult<SP_Feedbacks_GetAll_Result> SP_Feedbacks_GetAll()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_Feedbacks_GetAll_Result>("SP_Feedbacks_GetAll");
        }
    
        public virtual ObjectResult<SP_Feedbacks_GetByID_Result> SP_Feedbacks_GetByID(Nullable<System.Guid> iD)
        {
            var iDParameter = iD.HasValue ?
                new ObjectParameter("ID", iD) :
                new ObjectParameter("ID", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_Feedbacks_GetByID_Result>("SP_Feedbacks_GetByID", iDParameter);
        }
    
        public virtual int SP_Feedbacks_INSERT(Nullable<System.Guid> iD, string custommerName, string phoneNumber, string email, string noiDung, Nullable<System.DateTime> createDate)
        {
            var iDParameter = iD.HasValue ?
                new ObjectParameter("ID", iD) :
                new ObjectParameter("ID", typeof(System.Guid));
    
            var custommerNameParameter = custommerName != null ?
                new ObjectParameter("CustommerName", custommerName) :
                new ObjectParameter("CustommerName", typeof(string));
    
            var phoneNumberParameter = phoneNumber != null ?
                new ObjectParameter("PhoneNumber", phoneNumber) :
                new ObjectParameter("PhoneNumber", typeof(string));
    
            var emailParameter = email != null ?
                new ObjectParameter("Email", email) :
                new ObjectParameter("Email", typeof(string));
    
            var noiDungParameter = noiDung != null ?
                new ObjectParameter("NoiDung", noiDung) :
                new ObjectParameter("NoiDung", typeof(string));
    
            var createDateParameter = createDate.HasValue ?
                new ObjectParameter("CreateDate", createDate) :
                new ObjectParameter("CreateDate", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_Feedbacks_INSERT", iDParameter, custommerNameParameter, phoneNumberParameter, emailParameter, noiDungParameter, createDateParameter);
        }
    
        public virtual int SP_Feedbacks_UPDATE(Nullable<System.Guid> iD, string custommerName, string phoneNumber, string email, string noiDung, Nullable<System.DateTime> createDate)
        {
            var iDParameter = iD.HasValue ?
                new ObjectParameter("ID", iD) :
                new ObjectParameter("ID", typeof(System.Guid));
    
            var custommerNameParameter = custommerName != null ?
                new ObjectParameter("CustommerName", custommerName) :
                new ObjectParameter("CustommerName", typeof(string));
    
            var phoneNumberParameter = phoneNumber != null ?
                new ObjectParameter("PhoneNumber", phoneNumber) :
                new ObjectParameter("PhoneNumber", typeof(string));
    
            var emailParameter = email != null ?
                new ObjectParameter("Email", email) :
                new ObjectParameter("Email", typeof(string));
    
            var noiDungParameter = noiDung != null ?
                new ObjectParameter("NoiDung", noiDung) :
                new ObjectParameter("NoiDung", typeof(string));
    
            var createDateParameter = createDate.HasValue ?
                new ObjectParameter("CreateDate", createDate) :
                new ObjectParameter("CreateDate", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_Feedbacks_UPDATE", iDParameter, custommerNameParameter, phoneNumberParameter, emailParameter, noiDungParameter, createDateParameter);
        }
    
        public virtual ObjectResult<sp_helpdiagramdefinition_Result> sp_helpdiagramdefinition(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_helpdiagramdefinition_Result>("sp_helpdiagramdefinition", diagramnameParameter, owner_idParameter);
        }
    
        public virtual ObjectResult<sp_helpdiagrams_Result> sp_helpdiagrams(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_helpdiagrams_Result>("sp_helpdiagrams", diagramnameParameter, owner_idParameter);
        }
    
        public virtual int SP_Medicals_DELETE(Nullable<System.Guid> iD)
        {
            var iDParameter = iD.HasValue ?
                new ObjectParameter("ID", iD) :
                new ObjectParameter("ID", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_Medicals_DELETE", iDParameter);
        }
    
        public virtual ObjectResult<SP_Medicals_GetAll_Result> SP_Medicals_GetAll()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_Medicals_GetAll_Result>("SP_Medicals_GetAll");
        }
    
        public virtual ObjectResult<SP_Medicals_GetByID_Result> SP_Medicals_GetByID(Nullable<System.Guid> iD)
        {
            var iDParameter = iD.HasValue ?
                new ObjectParameter("ID", iD) :
                new ObjectParameter("ID", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_Medicals_GetByID_Result>("SP_Medicals_GetByID", iDParameter);
        }
    
        public virtual int SP_Medicals_INSERT(Nullable<System.Guid> iD, string name, string description, string images)
        {
            var iDParameter = iD.HasValue ?
                new ObjectParameter("ID", iD) :
                new ObjectParameter("ID", typeof(System.Guid));
    
            var nameParameter = name != null ?
                new ObjectParameter("Name", name) :
                new ObjectParameter("Name", typeof(string));
    
            var descriptionParameter = description != null ?
                new ObjectParameter("Description", description) :
                new ObjectParameter("Description", typeof(string));
    
            var imagesParameter = images != null ?
                new ObjectParameter("Images", images) :
                new ObjectParameter("Images", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_Medicals_INSERT", iDParameter, nameParameter, descriptionParameter, imagesParameter);
        }
    
        public virtual int SP_Medicals_UPDATE(Nullable<System.Guid> iD, string name, string description, string images)
        {
            var iDParameter = iD.HasValue ?
                new ObjectParameter("ID", iD) :
                new ObjectParameter("ID", typeof(System.Guid));
    
            var nameParameter = name != null ?
                new ObjectParameter("Name", name) :
                new ObjectParameter("Name", typeof(string));
    
            var descriptionParameter = description != null ?
                new ObjectParameter("Description", description) :
                new ObjectParameter("Description", typeof(string));
    
            var imagesParameter = images != null ?
                new ObjectParameter("Images", images) :
                new ObjectParameter("Images", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_Medicals_UPDATE", iDParameter, nameParameter, descriptionParameter, imagesParameter);
        }
    
        public virtual int SP_Menu_DELETE(Nullable<System.Guid> iD)
        {
            var iDParameter = iD.HasValue ?
                new ObjectParameter("ID", iD) :
                new ObjectParameter("ID", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_Menu_DELETE", iDParameter);
        }
    
        public virtual ObjectResult<SP_Menu_GetAll_Result> SP_Menu_GetAll()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_Menu_GetAll_Result>("SP_Menu_GetAll");
        }
    
        public virtual ObjectResult<SP_Menu_GetByID_Result> SP_Menu_GetByID(Nullable<System.Guid> iD)
        {
            var iDParameter = iD.HasValue ?
                new ObjectParameter("ID", iD) :
                new ObjectParameter("ID", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_Menu_GetByID_Result>("SP_Menu_GetByID", iDParameter);
        }
    
        public virtual int SP_Menu_INSERT(Nullable<System.Guid> iD, string menuItem1, string menuItem2, string menuItem3, string menuItem4, string menuItem5, string menuItem6)
        {
            var iDParameter = iD.HasValue ?
                new ObjectParameter("ID", iD) :
                new ObjectParameter("ID", typeof(System.Guid));
    
            var menuItem1Parameter = menuItem1 != null ?
                new ObjectParameter("MenuItem1", menuItem1) :
                new ObjectParameter("MenuItem1", typeof(string));
    
            var menuItem2Parameter = menuItem2 != null ?
                new ObjectParameter("MenuItem2", menuItem2) :
                new ObjectParameter("MenuItem2", typeof(string));
    
            var menuItem3Parameter = menuItem3 != null ?
                new ObjectParameter("MenuItem3", menuItem3) :
                new ObjectParameter("MenuItem3", typeof(string));
    
            var menuItem4Parameter = menuItem4 != null ?
                new ObjectParameter("MenuItem4", menuItem4) :
                new ObjectParameter("MenuItem4", typeof(string));
    
            var menuItem5Parameter = menuItem5 != null ?
                new ObjectParameter("MenuItem5", menuItem5) :
                new ObjectParameter("MenuItem5", typeof(string));
    
            var menuItem6Parameter = menuItem6 != null ?
                new ObjectParameter("MenuItem6", menuItem6) :
                new ObjectParameter("MenuItem6", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_Menu_INSERT", iDParameter, menuItem1Parameter, menuItem2Parameter, menuItem3Parameter, menuItem4Parameter, menuItem5Parameter, menuItem6Parameter);
        }
    
        public virtual int SP_Menu_UPDATE(Nullable<System.Guid> iD, string menuItem1, string menuItem2, string menuItem3, string menuItem4, string menuItem5, string menuItem6)
        {
            var iDParameter = iD.HasValue ?
                new ObjectParameter("ID", iD) :
                new ObjectParameter("ID", typeof(System.Guid));
    
            var menuItem1Parameter = menuItem1 != null ?
                new ObjectParameter("MenuItem1", menuItem1) :
                new ObjectParameter("MenuItem1", typeof(string));
    
            var menuItem2Parameter = menuItem2 != null ?
                new ObjectParameter("MenuItem2", menuItem2) :
                new ObjectParameter("MenuItem2", typeof(string));
    
            var menuItem3Parameter = menuItem3 != null ?
                new ObjectParameter("MenuItem3", menuItem3) :
                new ObjectParameter("MenuItem3", typeof(string));
    
            var menuItem4Parameter = menuItem4 != null ?
                new ObjectParameter("MenuItem4", menuItem4) :
                new ObjectParameter("MenuItem4", typeof(string));
    
            var menuItem5Parameter = menuItem5 != null ?
                new ObjectParameter("MenuItem5", menuItem5) :
                new ObjectParameter("MenuItem5", typeof(string));
    
            var menuItem6Parameter = menuItem6 != null ?
                new ObjectParameter("MenuItem6", menuItem6) :
                new ObjectParameter("MenuItem6", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_Menu_UPDATE", iDParameter, menuItem1Parameter, menuItem2Parameter, menuItem3Parameter, menuItem4Parameter, menuItem5Parameter, menuItem6Parameter);
        }
    
        public virtual int sp_renamediagram(string diagramname, Nullable<int> owner_id, string new_diagramname)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var new_diagramnameParameter = new_diagramname != null ?
                new ObjectParameter("new_diagramname", new_diagramname) :
                new ObjectParameter("new_diagramname", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_renamediagram", diagramnameParameter, owner_idParameter, new_diagramnameParameter);
        }
    
        public virtual int SP_Services_DELETE(Nullable<System.Guid> iD)
        {
            var iDParameter = iD.HasValue ?
                new ObjectParameter("ID", iD) :
                new ObjectParameter("ID", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_Services_DELETE", iDParameter);
        }
    
        public virtual ObjectResult<SP_Services_GetAll_Result> SP_Services_GetAll()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_Services_GetAll_Result>("SP_Services_GetAll");
        }
    
        public virtual ObjectResult<SP_Services_GetByID_Result> SP_Services_GetByID(Nullable<System.Guid> iD)
        {
            var iDParameter = iD.HasValue ?
                new ObjectParameter("ID", iD) :
                new ObjectParameter("ID", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_Services_GetByID_Result>("SP_Services_GetByID", iDParameter);
        }
    
        public virtual int SP_Services_INSERT(Nullable<System.Guid> iD, string titleDichvu, string titleGioiThieu, string titlePhongKham, string titleCosovatchat, string titleChuyenkhoa, string titleLienhe, string descriptionDichvu, string descriptionGioithieu, string descriptionPhongkham, string descriptionCosovatchat, string descriptionChuyenKhoa, string descriptionLienHe, string detailDichvu, string detailGioithieu, string detailPhongkham, string detailCosovatchat, string detailChuyenkhoa, string detailLienhe, string images, string address, string hotLine, string phone, string logo, string backGround, string slogan)
        {
            var iDParameter = iD.HasValue ?
                new ObjectParameter("ID", iD) :
                new ObjectParameter("ID", typeof(System.Guid));
    
            var titleDichvuParameter = titleDichvu != null ?
                new ObjectParameter("TitleDichvu", titleDichvu) :
                new ObjectParameter("TitleDichvu", typeof(string));
    
            var titleGioiThieuParameter = titleGioiThieu != null ?
                new ObjectParameter("TitleGioiThieu", titleGioiThieu) :
                new ObjectParameter("TitleGioiThieu", typeof(string));
    
            var titlePhongKhamParameter = titlePhongKham != null ?
                new ObjectParameter("TitlePhongKham", titlePhongKham) :
                new ObjectParameter("TitlePhongKham", typeof(string));
    
            var titleCosovatchatParameter = titleCosovatchat != null ?
                new ObjectParameter("TitleCosovatchat", titleCosovatchat) :
                new ObjectParameter("TitleCosovatchat", typeof(string));
    
            var titleChuyenkhoaParameter = titleChuyenkhoa != null ?
                new ObjectParameter("TitleChuyenkhoa", titleChuyenkhoa) :
                new ObjectParameter("TitleChuyenkhoa", typeof(string));
    
            var titleLienheParameter = titleLienhe != null ?
                new ObjectParameter("TitleLienhe", titleLienhe) :
                new ObjectParameter("TitleLienhe", typeof(string));
    
            var descriptionDichvuParameter = descriptionDichvu != null ?
                new ObjectParameter("DescriptionDichvu", descriptionDichvu) :
                new ObjectParameter("DescriptionDichvu", typeof(string));
    
            var descriptionGioithieuParameter = descriptionGioithieu != null ?
                new ObjectParameter("DescriptionGioithieu", descriptionGioithieu) :
                new ObjectParameter("DescriptionGioithieu", typeof(string));
    
            var descriptionPhongkhamParameter = descriptionPhongkham != null ?
                new ObjectParameter("DescriptionPhongkham", descriptionPhongkham) :
                new ObjectParameter("DescriptionPhongkham", typeof(string));
    
            var descriptionCosovatchatParameter = descriptionCosovatchat != null ?
                new ObjectParameter("DescriptionCosovatchat", descriptionCosovatchat) :
                new ObjectParameter("DescriptionCosovatchat", typeof(string));
    
            var descriptionChuyenKhoaParameter = descriptionChuyenKhoa != null ?
                new ObjectParameter("DescriptionChuyenKhoa", descriptionChuyenKhoa) :
                new ObjectParameter("DescriptionChuyenKhoa", typeof(string));
    
            var descriptionLienHeParameter = descriptionLienHe != null ?
                new ObjectParameter("DescriptionLienHe", descriptionLienHe) :
                new ObjectParameter("DescriptionLienHe", typeof(string));
    
            var detailDichvuParameter = detailDichvu != null ?
                new ObjectParameter("DetailDichvu", detailDichvu) :
                new ObjectParameter("DetailDichvu", typeof(string));
    
            var detailGioithieuParameter = detailGioithieu != null ?
                new ObjectParameter("DetailGioithieu", detailGioithieu) :
                new ObjectParameter("DetailGioithieu", typeof(string));
    
            var detailPhongkhamParameter = detailPhongkham != null ?
                new ObjectParameter("DetailPhongkham", detailPhongkham) :
                new ObjectParameter("DetailPhongkham", typeof(string));
    
            var detailCosovatchatParameter = detailCosovatchat != null ?
                new ObjectParameter("DetailCosovatchat", detailCosovatchat) :
                new ObjectParameter("DetailCosovatchat", typeof(string));
    
            var detailChuyenkhoaParameter = detailChuyenkhoa != null ?
                new ObjectParameter("DetailChuyenkhoa", detailChuyenkhoa) :
                new ObjectParameter("DetailChuyenkhoa", typeof(string));
    
            var detailLienheParameter = detailLienhe != null ?
                new ObjectParameter("DetailLienhe", detailLienhe) :
                new ObjectParameter("DetailLienhe", typeof(string));
    
            var imagesParameter = images != null ?
                new ObjectParameter("Images", images) :
                new ObjectParameter("Images", typeof(string));
    
            var addressParameter = address != null ?
                new ObjectParameter("Address", address) :
                new ObjectParameter("Address", typeof(string));
    
            var hotLineParameter = hotLine != null ?
                new ObjectParameter("HotLine", hotLine) :
                new ObjectParameter("HotLine", typeof(string));
    
            var phoneParameter = phone != null ?
                new ObjectParameter("Phone", phone) :
                new ObjectParameter("Phone", typeof(string));
    
            var logoParameter = logo != null ?
                new ObjectParameter("Logo", logo) :
                new ObjectParameter("Logo", typeof(string));
    
            var backGroundParameter = backGround != null ?
                new ObjectParameter("BackGround", backGround) :
                new ObjectParameter("BackGround", typeof(string));
    
            var sloganParameter = slogan != null ?
                new ObjectParameter("Slogan", slogan) :
                new ObjectParameter("Slogan", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_Services_INSERT", iDParameter, titleDichvuParameter, titleGioiThieuParameter, titlePhongKhamParameter, titleCosovatchatParameter, titleChuyenkhoaParameter, titleLienheParameter, descriptionDichvuParameter, descriptionGioithieuParameter, descriptionPhongkhamParameter, descriptionCosovatchatParameter, descriptionChuyenKhoaParameter, descriptionLienHeParameter, detailDichvuParameter, detailGioithieuParameter, detailPhongkhamParameter, detailCosovatchatParameter, detailChuyenkhoaParameter, detailLienheParameter, imagesParameter, addressParameter, hotLineParameter, phoneParameter, logoParameter, backGroundParameter, sloganParameter);
        }
    
        public virtual int SP_Services_UPDATE(Nullable<System.Guid> iD, string titleDichvu, string titleGioiThieu, string titlePhongKham, string titleCosovatchat, string titleChuyenkhoa, string titleLienhe, string descriptionDichvu, string descriptionGioithieu, string descriptionPhongkham, string descriptionCosovatchat, string descriptionChuyenKhoa, string descriptionLienHe, string detailDichvu, string detailGioithieu, string detailPhongkham, string detailCosovatchat, string detailChuyenkhoa, string detailLienhe, string images, string address, string hotLine, string phone, string logo, string backGround, string slogan)
        {
            var iDParameter = iD.HasValue ?
                new ObjectParameter("ID", iD) :
                new ObjectParameter("ID", typeof(System.Guid));
    
            var titleDichvuParameter = titleDichvu != null ?
                new ObjectParameter("TitleDichvu", titleDichvu) :
                new ObjectParameter("TitleDichvu", typeof(string));
    
            var titleGioiThieuParameter = titleGioiThieu != null ?
                new ObjectParameter("TitleGioiThieu", titleGioiThieu) :
                new ObjectParameter("TitleGioiThieu", typeof(string));
    
            var titlePhongKhamParameter = titlePhongKham != null ?
                new ObjectParameter("TitlePhongKham", titlePhongKham) :
                new ObjectParameter("TitlePhongKham", typeof(string));
    
            var titleCosovatchatParameter = titleCosovatchat != null ?
                new ObjectParameter("TitleCosovatchat", titleCosovatchat) :
                new ObjectParameter("TitleCosovatchat", typeof(string));
    
            var titleChuyenkhoaParameter = titleChuyenkhoa != null ?
                new ObjectParameter("TitleChuyenkhoa", titleChuyenkhoa) :
                new ObjectParameter("TitleChuyenkhoa", typeof(string));
    
            var titleLienheParameter = titleLienhe != null ?
                new ObjectParameter("TitleLienhe", titleLienhe) :
                new ObjectParameter("TitleLienhe", typeof(string));
    
            var descriptionDichvuParameter = descriptionDichvu != null ?
                new ObjectParameter("DescriptionDichvu", descriptionDichvu) :
                new ObjectParameter("DescriptionDichvu", typeof(string));
    
            var descriptionGioithieuParameter = descriptionGioithieu != null ?
                new ObjectParameter("DescriptionGioithieu", descriptionGioithieu) :
                new ObjectParameter("DescriptionGioithieu", typeof(string));
    
            var descriptionPhongkhamParameter = descriptionPhongkham != null ?
                new ObjectParameter("DescriptionPhongkham", descriptionPhongkham) :
                new ObjectParameter("DescriptionPhongkham", typeof(string));
    
            var descriptionCosovatchatParameter = descriptionCosovatchat != null ?
                new ObjectParameter("DescriptionCosovatchat", descriptionCosovatchat) :
                new ObjectParameter("DescriptionCosovatchat", typeof(string));
    
            var descriptionChuyenKhoaParameter = descriptionChuyenKhoa != null ?
                new ObjectParameter("DescriptionChuyenKhoa", descriptionChuyenKhoa) :
                new ObjectParameter("DescriptionChuyenKhoa", typeof(string));
    
            var descriptionLienHeParameter = descriptionLienHe != null ?
                new ObjectParameter("DescriptionLienHe", descriptionLienHe) :
                new ObjectParameter("DescriptionLienHe", typeof(string));
    
            var detailDichvuParameter = detailDichvu != null ?
                new ObjectParameter("DetailDichvu", detailDichvu) :
                new ObjectParameter("DetailDichvu", typeof(string));
    
            var detailGioithieuParameter = detailGioithieu != null ?
                new ObjectParameter("DetailGioithieu", detailGioithieu) :
                new ObjectParameter("DetailGioithieu", typeof(string));
    
            var detailPhongkhamParameter = detailPhongkham != null ?
                new ObjectParameter("DetailPhongkham", detailPhongkham) :
                new ObjectParameter("DetailPhongkham", typeof(string));
    
            var detailCosovatchatParameter = detailCosovatchat != null ?
                new ObjectParameter("DetailCosovatchat", detailCosovatchat) :
                new ObjectParameter("DetailCosovatchat", typeof(string));
    
            var detailChuyenkhoaParameter = detailChuyenkhoa != null ?
                new ObjectParameter("DetailChuyenkhoa", detailChuyenkhoa) :
                new ObjectParameter("DetailChuyenkhoa", typeof(string));
    
            var detailLienheParameter = detailLienhe != null ?
                new ObjectParameter("DetailLienhe", detailLienhe) :
                new ObjectParameter("DetailLienhe", typeof(string));
    
            var imagesParameter = images != null ?
                new ObjectParameter("Images", images) :
                new ObjectParameter("Images", typeof(string));
    
            var addressParameter = address != null ?
                new ObjectParameter("Address", address) :
                new ObjectParameter("Address", typeof(string));
    
            var hotLineParameter = hotLine != null ?
                new ObjectParameter("HotLine", hotLine) :
                new ObjectParameter("HotLine", typeof(string));
    
            var phoneParameter = phone != null ?
                new ObjectParameter("Phone", phone) :
                new ObjectParameter("Phone", typeof(string));
    
            var logoParameter = logo != null ?
                new ObjectParameter("Logo", logo) :
                new ObjectParameter("Logo", typeof(string));
    
            var backGroundParameter = backGround != null ?
                new ObjectParameter("BackGround", backGround) :
                new ObjectParameter("BackGround", typeof(string));
    
            var sloganParameter = slogan != null ?
                new ObjectParameter("Slogan", slogan) :
                new ObjectParameter("Slogan", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_Services_UPDATE", iDParameter, titleDichvuParameter, titleGioiThieuParameter, titlePhongKhamParameter, titleCosovatchatParameter, titleChuyenkhoaParameter, titleLienheParameter, descriptionDichvuParameter, descriptionGioithieuParameter, descriptionPhongkhamParameter, descriptionCosovatchatParameter, descriptionChuyenKhoaParameter, descriptionLienHeParameter, detailDichvuParameter, detailGioithieuParameter, detailPhongkhamParameter, detailCosovatchatParameter, detailChuyenkhoaParameter, detailLienheParameter, imagesParameter, addressParameter, hotLineParameter, phoneParameter, logoParameter, backGroundParameter, sloganParameter);
        }
    
        public virtual int sp_upgraddiagrams()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_upgraddiagrams");
        }
    
        public virtual int SP_User_DELETE(string userName)
        {
            var userNameParameter = userName != null ?
                new ObjectParameter("UserName", userName) :
                new ObjectParameter("UserName", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_User_DELETE", userNameParameter);
        }
    
        public virtual ObjectResult<SP_User_GetAll_Result> SP_User_GetAll()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_User_GetAll_Result>("SP_User_GetAll");
        }
    
        public virtual ObjectResult<SP_User_GetByUserName_Result> SP_User_GetByUserName(string userName)
        {
            var userNameParameter = userName != null ?
                new ObjectParameter("UserName", userName) :
                new ObjectParameter("UserName", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_User_GetByUserName_Result>("SP_User_GetByUserName", userNameParameter);
        }
    
        public virtual int SP_User_INSERT(string userName, string name, string passWord)
        {
            var userNameParameter = userName != null ?
                new ObjectParameter("UserName", userName) :
                new ObjectParameter("UserName", typeof(string));
    
            var nameParameter = name != null ?
                new ObjectParameter("Name", name) :
                new ObjectParameter("Name", typeof(string));
    
            var passWordParameter = passWord != null ?
                new ObjectParameter("PassWord", passWord) :
                new ObjectParameter("PassWord", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_User_INSERT", userNameParameter, nameParameter, passWordParameter);
        }
    
        public virtual int SP_User_UPDATE(string userName, string name, string passWord)
        {
            var userNameParameter = userName != null ?
                new ObjectParameter("UserName", userName) :
                new ObjectParameter("UserName", typeof(string));
    
            var nameParameter = name != null ?
                new ObjectParameter("Name", name) :
                new ObjectParameter("Name", typeof(string));
    
            var passWordParameter = passWord != null ?
                new ObjectParameter("PassWord", passWord) :
                new ObjectParameter("PassWord", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_User_UPDATE", userNameParameter, nameParameter, passWordParameter);
        }
    }
}
